#!/usr/bin/perl

# This is the main driver program to test the subroutine
# USAGE match FILE
open(FP,"$ARGV[0]");

while (<FP>) { chop;
  $string = &match($_,"sin","(",")");   # match pattern "sin(.....)"
  print "$string\n";

}

# subroutine to match balancing ()
# USAGE: &match($string,$pat,$lbracket,$rbracket)
#        matches $pat(....) in $string if $lbracket is ( and $rbracket )
sub match
{
  local($pat) = $_[1];
  local($sb) = "\\";
  local($lb) = $_[2]; local($rb) = $_[3];
  $_ = $_[0];
  if(s/.*$pat$sb$lb//) { s/\'$sb$lb\'/\'\ca\'/g; s/\'$sb$rb\'/\'\cb\'/g;
    s/\\$sb$lb/\\\ca/g; s/\\$sb$rb/\\\cb/g;
    while (s/$sb$lb([^$lb$rb]*)$sb$rb/\ca\1\cb/) { ; }
    if (s/$sb$rb.*/$rb/) { s/\ca/$lb/g; s/\cb/$rb/g; s/^/$pat$lb/; }
    else { $_ = ""; }
    return $_;
    }
  else { return ""; }

} 
