#!/bin/bash
#
# $Id: split_trans,v 1.5 2005/02/16 07:58:28 psy Exp $
#
# Produces a set of BibTeX search-and-replace calls.  It should be
# run on a file trans.bst produced by the following command line:
#
# xsltproc latex2unicode.xsl ent.xml | uniq >trans.bst
#
# You should probably manually edit trans.bst beforehand to remove any
# undesirable lines.

# Usage instructions
ME=`basename $0`
USAGE="Usage: $ME file"

# Error function
function error() # errormessage
{
    echo "$ME: $1" 1>&2
}

# Process command line
if [ $# -ne 1 ]
then
        echo "$USAGE"
        exit 1
fi

if [ ! -e "$1" ]
then
    error "file '$1' does not exist"
    exit 1
fi

tmpfile=/tmp/split.trans.$$
grep -v '^%' $1 >$tmpfile || error "cannot create temp file $tmpfile"

i=1
func=1
words=0
lines=$(wc -l <$tmpfile)
echo "FUNCTION {latex2html.$func}"
echo "{"
while [ $i -le $lines ]
do
     newwords=$(sed -n "${i}p" $tmpfile | wc -w)
     if [ $((words + newwords)) -ge 100 ]
     then
         words=0
         let func=func+1
         echo -e "}\n\nFUNCTION {latex2html.$func}\n{"
     fi
     sed -n "${i}p" $tmpfile
     let i=i+1
     let words=words+newwords
done
echo -e "}\n"

echo "FUNCTION {latex2html}"
echo "{ use.internal.latex2html #0 ="
echo "    'skip$"
echo "    {"
i=1
while [ $i -le $func ]
do
    echo "      latex2html.$i"
    let i=i+1
done
echo "    }"
echo "  if$"
echo "}"
echo

rm $tmpfile
