#!/bin/bash
cd ~/Documents/resume/publications
if [[ ! -e miller.aux ]]
then
    latex miller
fi
bibtex miller || exit 1
kwrite miller.html >&/dev/null &
scp miller.bib onza:www/files.nothingisreal.com/publications/Tristan_Miller/miller.bib
rsync -Pavy covers/ onza:www/files.nothingisreal.com/publications/Tristan_Miller/covers/
